//paradef.h

#ifndef  NET_CARD_PATH

#define  NET_CARD_PATH           "SYSTEM\\CurrentControlSet\\Services\\MPCC"
#define      PARAMETERS          "Parameters"
#define         ADDR_PAIR        "AddrPair"
#define         BAUDRATE         "BAUDRATE0"
#define         LINKCLK          "LINKCLK0"
#define         LINKDEV          "LINKDEV0"
#define         X121ADDR         "X121ADDR0"



#endif
