//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by fig.rc
//
#define IDD_FIG_DIALOG                  102
#define IDD_IPREAD_DIALOG               103
#define IDD_HUI_DIALOG                  104
#define IDR_MAINFRAME                   128
#define ID_ADVANCED                     1000
#define ID_X121ADDR                     1004
#define IDC_BTN_ADD                     1005
#define IDC_LIST                        1006
#define IDC_BTN_DELETE                  1007
#define IDC_LINKCLK                     1007
#define IDC_IPADDR_1                    1008
#define IDC_RADIO2                      1008
#define IDC_IPADDR_2                    1009
#define IDC_IPADDR_3                    1010
#define IDC_IPADDR_4                    1011
#define ID_MYOK                         1012
#define IDC_BAUDRATE                    1012
#define IDC_X121ADDR                    1013
#define IDC_RADIO7                      1014
#define IDC_RADIO8                      1015
#define IDC_RADIO9                      1016
#define IDC_WORKMODE                    1019
#define IDC_RADIO11                     1020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
